apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-repo
  name: test-repo
  labels:
    app: test-repo
spec:
  selector:
    matchLabels:
      app: test-repo
  template:
    metadata:
      labels:
        app: test-repo
        name: test-repo
    spec:
      containers:
        - name: test-repo
          image: mahendraintelops/test-repo/test-repo
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 4500
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        